services:
  db:
    ports: !override []

  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports: !override
      - "127.0.0.1:8090:8080"

  frontend:
    ports: !override
      - "127.0.0.1:8081:80"
