package io.muzoo.ssc.plogit.domain;

public enum ActivityType {
    OSINT,
    RECONNAISSANCE,
    PORT_SCANNING,
    SERVICE_ENUMERATION,
    WEB_APPLICATION_TESTING,
    VULNERABILITY_SCANNING,
    EXPLOITATION,
    POST_EXPLOITATION,
    PRIVILEGE_ESCALATION,
    LATERAL_MOVEMENT,
    SOCIAL_ENGINEERING,
    PHYSICAL_ACCESS,
    WIRELESS_TESTING,
    MANUAL_TESTING,
    OTHER
}
